name: Build (checkers)

on:
  push:
    branches: [master]
    tags-ignore: ['*']
    paths: ['checkers/**']

  pull_request:
    branches: [master]    
    paths: ['checkers/**']

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macOS-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: make all
        run: |
          cd checkers
          mkdir build
          make all

      - name: Set GOOS (windows)
        if: matrix.os == 'windows-latest'
        run: echo "GOOS=windows" >> $GITHUB_ENV
      
      - name: Set GOOS (linux)
        if: matrix.os == 'ubuntu-latest'
        run: echo "GOOS=linux" >> $GITHUB_ENV

      - name: Set GOOS (darwin)
        if: matrix.os == 'macOS-latest'
        run: echo "GOOS=darwin" >> $GITHUB_ENV

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cpt-checker_${{ env.GOOS }}
          path: |
            checkers/build/*
            checkers/meta.yaml